format = """\
[](bg:none fg:#bcbcbc)\
[](bg:#bcbcbc fg:#282A36)\
[](fg:#bcbcbc bg:#c792ea)\
$directory\
[](fg:#c792ea bg:#fce94f)\
$git_branch$git_status\
[](fg:#fce94f bg:none)\
$cmd_duration\
$line_break\
$character\
"""

[directory]
format = "[ 󰉋 $path ]($style)"
style = "fg:#ffffff bg:#c792ea"
truncate_to_repo = false

[git_branch]
format = "[  $branch ]($style)"
style = "fg:#282A36 bg:#fce94f"

[git_status]
format = "[ $all_status ]($style)"
style = "fg:#282A36 bg:#fce94f"

[cmd_duration]
format = " [$duration]($style)"
style = "fg:#6272a4"
min_time = 0
show_milliseconds = true

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"